blank_issues_enabled: false
contact_links:
  - name: ❓ Support question or technical issue
    url: https://github.com/Abrynos/Implement.Net/discussions
    about: All technical questions can be asked here
  - name: 🗯️ Negative feedback, complaints and demands
    url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    about: We're taking those very seriously
